CREATE TABLE IF NOT EXISTS ORDER_PRODUCT
(
	ORDERPRODUCT_ID VARCHAR(10),
	PRODUCT_ID VARCHAR(10),
	AMOUNT INT,
	ORDER_ID VARCHAR(10),
	CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT,
	CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDER,
	CONSTRAINT ORDER_PRODUCT_PK PRIMARY KEY (ORDERPRODUCT_ID)
);