CREATE TABLE ORDERS
(
	ORDER_ID INT(10) AUTO_INCREMENT,
	AMOUNT INT(10) NOT NULL,
	DATE TIMESTAMP,
	USER_ID INT(10) NOT NULL,
	CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER,
	CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID)
);