CREATE TABLE PRODUCT
( 
	PRODUCT_ID INT(10) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(10) NOT NULL,
	DESCRIPTION VARCHAR(255),
	PRICE FLOAT NOT NULL DEFAULT 0,
	CATEGORY VARCHAR(10) NOT NULL DEFAULT '1',
	CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT_ID)
);